[workspace]
resolver = "2"
members = ["day1", "day2", "day3", "day4"]

[package]
name = "aoc-2024"
version = "24.12.24"
description = "Advent of Code written in Rust"
edition = "2021"
authors = ["Shirosaka <shiro@shirosaka.dev>"]

[dependencies]
clap = { version = "4.5.22", features = ["derive"] }
